apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-counter-app
data:
  fluent.conf: |
    <source>
      type tail
      format none
      path /var/log/1.log
      pos_file /var/log/1.log.pos
      tag count.format1
    </source>

    <match **>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      index_name "#{ENV['DOMAIN_UID']}"
      type_name fluentd
      default_elasticsearch_version 7
      log_es_400_reason true
    </match>

